[book]
authors = ["Cardinal Cryptography"]
language = "en"
description = "Documentation of the rust implementation of Aleph protocol"
multilingual = false
src = "guide/src"
title = "Rush - Aleph in Rust"

[build]
build-dir = "guide/book"
create-missing = false
