[package]
name = "rush"
version = "0.3.0"
edition = "2018"
authors = ["Cardinal Cryptography"]
categories = ["algorithms", "data-structures", "cryptography", "database"]
documentation = "https://docs.rs/?"
homepage = "https://alephzero.org"
repository = "https://github.com/cardinal-cryptography/?"
keywords = ["aleph", "asynchronous", "consensus", "bft", "blockchain", "distributed-systems"]
license = "Apache-2.0"
readme = "README.md"

description = """
TODO expand
An implementation of the Aleph asynchronous BFT consensus protocol.
"""


[dependencies]
bit-vec = "0.6"
parking_lot = "0.11.1"
futures = "0.3.9"
tokio = { version = "0.2.21", features = ["macros", "rt-threaded", "time"] }
mini-redis = "0.4"
derive_more = "0.99.7"
serde = { version = "1.0.110", features = ["derive"] }
futures-timer = "3.0.2"
log = "0.4.14"
env_logger = "0.8.3"
codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive"] }
rand = "0.8.3"
async-trait = "0"

[dev-dependencies]
libp2p = { version ="0", features = ["mdns", "tcp-tokio"]}
