name: Sync Cardinal-Cryptography repo with Aleph-Zero-Foundation repo

on:
  push:
    branches: [AZ-62-fix-sync-with-foundation-repo]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Push to Aleph-Zero-Foundation
        run: |
          git config -l
          git remote add alephzero https://maciejnems:${{ secrets.SYNC_FOUNDATION }}@github.com/aleph-zero-foundation/AlephBFT.git
          git push alephzero
