name: Sync Cardinal-Cryptography repo with Aleph-Zero-Foundation repo

on:
  push:
    branches: [AZ-62-fix-sync-with-foundation-repo]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: Push to Aleph-Zero-Foundation
        run: |
          git config --global user.name 'sync-foundation'
          git config --global user.email 'sync@alephzero.org'
          git remote add alephzero https://x-access-token:${{ secrets.SYNCAZF }}@github.com/aleph-zero-foundation/AlephBFT
          git push alephzero
