name: Sync Cardinal-Cryptography repo with Aleph-Zero-Foundation repo

on:
  push:
    branches: [AZ-62-fix-sync-with-foundation-repo]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@AZ-62-fix-sync-with-foundation-repo
      - name: Push to Aleph-Zero-Foundation
        run: |
          git remote add alephzero https://x-access-token:${{ secrets.SYNC_FOUNDATION }}@github.com/aleph-zero-foundation/AlephBFT
          git push alephzero
